# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: suggestions/suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'suggestions/suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsuggestions/suggestions.proto\"$\n\x11SuggestionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\")\n\x12SuggestionResponse\x12\x13\n\x0bsuggestions\x18\x01 \x03(\t2H\n\x0bSuggestions\x12\x39\n\x0eGetSuggestions\x12\x12.SuggestionRequest\x1a\x13.SuggestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions.suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUGGESTIONREQUEST']._serialized_start=33
  _globals['_SUGGESTIONREQUEST']._serialized_end=69
  _globals['_SUGGESTIONRESPONSE']._serialized_start=71
  _globals['_SUGGESTIONRESPONSE']._serialized_end=112
  _globals['_SUGGESTIONS']._serialized_start=114
  _globals['_SUGGESTIONS']._serialized_end=186
# @@protoc_insertion_point(module_scope)
