version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html

  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
    depends_on:
      - fraud_detection
      - transaction_verification
      - suggestions
    networks:
      - app-network

  fraud_detection:
    build:
      context: ./
      dockerfile: ./microservices/fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/fraud_detection/src/fraud_detection.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/fraud_detection/src:/app/microservices/fraud_detection/src
    networks:
      - app-network

  transaction_verification:
    build:
      context: ./
      dockerfile: ./microservices/transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/transaction_verification/src/transaction_verification.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/transaction_verification/src:/app/microservices/transaction_verification/src
    networks:
      - app-network

  suggestions:
    build:
      context: ./
      dockerfile: ./microservices/suggestions/Dockerfile
    ports:
      - 50053:50053
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/suggestions/src/suggestions.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/suggestions/src:/app/microservices/suggestions/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
