version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
  
  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
  
  fraud_detection:
    build:
      context: ./
      dockerfile: ./fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
      - PYTHONPATH=/app/utils
    volumes:
      - ./fraud_detection/src:/app/fraud_detection/src
      - ./utils:/app/utils
  
  suggestions:
    build:
      context: ./
      dockerfile: ./suggestions/Dockerfile
    ports:
      - 50053:50053  # Changed from 50052 to match your app.py configuration
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app/utils
    volumes:
      - ./suggestions/src:/app/suggestions/src
      - ./utils:/app/utils
  
  transaction_verification:
    build:
      context: ./
      dockerfile: ./transaction_verification/Dockerfile
    ports:
      - 50052:50052  # This should be the port your service listens on in app.py
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONPATH=/app/utils
    volumes:
      - ./transaction_verification/src:/app/transaction_verification/src
      - ./utils:/app/utils