version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html

  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
    depends_on:
      - fraud_detection
      - transaction_verification
      - suggestions
    networks:
      - app-network

  fraud_detection:
    build:
      context: ./
      dockerfile: ./microservices/fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/fraud_detection/src/fraud_detection.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/fraud_detection/src:/app/microservices/fraud_detection/src
    networks:
      - app-network

  transaction_verification:
    build:
      context: ./
      dockerfile: ./microservices/transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/transaction_verification/src/transaction_verification.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/transaction_verification/src:/app/microservices/transaction_verification/src
    networks:
      - app-network

  suggestions:
    build:
      context: ./
      dockerfile: ./microservices/suggestions/Dockerfile
    ports:
      - 50053:50053
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/suggestions/src/suggestions.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/suggestions/src:/app/microservices/suggestions/src
    networks:
      - app-network

  payment:
    build:
      context: ./
      dockerfile: ./microservices/payment/Dockerfile
    ports:
      - 50064:50064
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/payment/src/payment_service.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/payment/src:/app/microservices/payment/src
    networks:
      - app-network

  order_queue:
    build:
      context: ./
      dockerfile: ./microservices/order_queue/Dockerfile
    ports:
      - 50054:50054
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/order_queue/src/order_queue.py
    volumes:
      - ./utils:/app/utils
      - ./microservices/order_queue/src:/app/microservices/order_queue/src
    networks:
      - app-network

  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    networks:
      - app-network

  order_executor_1:
    build:
      context: ./
      dockerfile: ./microservices/order_executor/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/order_executor/src/app.py
      - ZK_HOST=zookeeper:2181
      - SERVICE_NAME=order_executor
      - ORDER_EXECUTOR_REPLICAS=3
      - NODE_ID=1
      - LISTENING_PORT=50055
    volumes:
      - ./utils:/app/utils
      - ./microservices/order_executor/src:/app/microservices/order_executor/src
    depends_on:
      - order_queue
      - zookeeper
    networks:
      - app-network

  order_executor_2:
    build:
      context: ./
      dockerfile: ./microservices/order_executor/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/order_executor/src/app.py
      - ZK_HOST=zookeeper:2181
      - SERVICE_NAME=order_executor
      - ORDER_EXECUTOR_REPLICAS=3
      - NODE_ID=2
      - LISTENING_PORT=50056
    volumes:
      - ./utils:/app/utils
      - ./microservices/order_executor/src:/app/microservices/order_executor/src
    depends_on:
      - order_queue
      - zookeeper
    networks:
      - app-network

  order_executor_3:
    build:
      context: ./
      dockerfile: ./microservices/order_executor/Dockerfile
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/order_executor/src/app.py
      - ZK_HOST=zookeeper:2181
      - SERVICE_NAME=order_executor
      - ORDER_EXECUTOR_REPLICAS=3
      - NODE_ID=3
      - LISTENING_PORT=50057
    volumes:
      - ./utils:/app/utils
      - ./microservices/order_executor/src:/app/microservices/order_executor/src
    depends_on:
      - order_queue
      - zookeeper
    networks:
      - app-network

  books_primary:
    build:
      context: ./
      dockerfile: ./microservices/books_db/Dockerfile
    ports:
      - "50061:50061"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/books_db/src/replica.py
      - REPLICA_ROLE=primary
      - LISTENING_PORT=50061
      - BACKUP_PORTS=50062,50063
    volumes:
      - ./utils:/app/utils
      - ./microservices/books_db/src:/app/microservices/books_db/src
    networks:
      - app-network

  books_backup1:
    build:
      context: ./
      dockerfile: ./microservices/books_db/Dockerfile
    ports:
      - "50062:50062"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/books_db/src/replica.py
      - REPLICA_ROLE=backup
      - LISTENING_PORT=50062
    volumes:
      - ./utils:/app/utils
      - ./microservices/books_db/src:/app/microservices/books_db/src
    networks:
      - app-network

  books_backup2:
    build:
      context: ./
      dockerfile: ./microservices/books_db/Dockerfile
    ports:
      - "50063:50063"
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/microservices/books_db/src/replica.py
      - REPLICA_ROLE=backup
      - LISTENING_PORT=50063
    volumes:
      - ./utils:/app/utils
      - ./microservices/books_db/src:/app/microservices/books_db/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
