version: "3"

services:
  frontend:
    build:
      context: ./frontend/src
      dockerfile: Dockerfile
    ports:
      # Expose port 8080 on the host, and map port 80 of the container to port 8080 on the host
      # Access the application at http://localhost:8080
      - "8080:80"
    volumes:
      # Mount the frontend directory
      - ./frontend/src:/usr/share/nginx/html
    networks:
      - app-network

  orchestrator:
    build:
      context: ./orchestrator/src
      dockerfile: Dockerfile
    ports:
      - "8081:5000"
    environment:
      # Pass the environment variables to the container
      # The PYTHONUNBUFFERED environment variable ensures that the output from the application is logged to the console
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./utils/pb/src:/app/utils/pb/src
      - ./orchestrator/src:/app/orchestrator/src
  fraud_detection:
    build:
      context: ./microservices/fraud_detection/src
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      # Pass the environment variables to the container
      # The PYTHONUNBUFFERED environment variable ensures that the output from the application is logged to the console
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./utils/pb/src:/app/utils/pb/src
      - ./microservices/fraud_detection/src:/app/microservices/fraud_detection/src
    networks:
      - app-network

  transaction_verification:
    build:
      context: ./microservices/transaction_verification/src
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./utils/pb/src:/app/utils/pb/src
      - ./microservices/transaction_verification/src:/app/microservices/transaction_verification/src
    networks:
      - app-network

  suggestions:
    build:
      context: ./microservices/suggestions/src
      dockerfile: Dockerfile
    env_file:
      - ./microservices/suggestions/src/.env
    ports:
      - "50053:50053"
    environment:
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./utils/pb/src:/app/utils/pb/src
      - ./microservices/suggestions/src:/app/microservices/suggestions/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
