# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x0epaymentservice\"2\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"!\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xeb\x01\n\x0ePaymentService\x12J\n\x07Prepare\x12\x1e.paymentservice.PrepareRequest\x1a\x1f.paymentservice.PrepareResponse\x12G\n\x06\x43ommit\x12\x1d.paymentservice.CommitRequest\x1a\x1e.paymentservice.CommitResponse\x12\x44\n\x05\x41\x62ort\x12\x1c.paymentservice.AbortRequest\x1a\x1d.paymentservice.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREPAREREQUEST']._serialized_start=33
  _globals['_PREPAREREQUEST']._serialized_end=83
  _globals['_PREPARERESPONSE']._serialized_start=85
  _globals['_PREPARERESPONSE']._serialized_end=117
  _globals['_COMMITREQUEST']._serialized_start=119
  _globals['_COMMITREQUEST']._serialized_end=152
  _globals['_COMMITRESPONSE']._serialized_start=154
  _globals['_COMMITRESPONSE']._serialized_end=187
  _globals['_ABORTREQUEST']._serialized_start=189
  _globals['_ABORTREQUEST']._serialized_end=221
  _globals['_ABORTRESPONSE']._serialized_start=223
  _globals['_ABORTRESPONSE']._serialized_end=255
  _globals['_PAYMENTSERVICE']._serialized_start=258
  _globals['_PAYMENTSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
