syntax = "proto3";

package transaction;

message VectorClock {
  map<string, int32> clock = 1;
}

message TransactionUser {
  string name = 1;
  string contact = 2;
}

message CreditCard {
  string number = 1;
  string expirationDate = 2;
  string cvv = 3;
}

message TransactionItem {
  string name = 1;
  int32 quantity = 2;
}

message TransactionBillingAddress {
  string street = 1;
  string city = 2;
  string country = 3;
}

message TransactionRequest {
  string orderId = 1;
  TransactionUser user = 2;
  CreditCard creditCard = 3;
  repeated TransactionItem items = 4;
  TransactionBillingAddress billingAddress = 5;
  VectorClock vectorClock = 6;
}

message TransactionResponse {
  bool isValid = 1;
  VectorClock vectorClock = 2;
}

message UpdateClockRequest {
  string orderId = 1;
  VectorClock vectorClock = 2;
}

message UpdateClockResponse {
  VectorClock vectorClock = 1;
}

service TransactionService {
  rpc VerifyTransaction (TransactionRequest) returns (TransactionResponse);
  rpc UpdateClock (UpdateClockRequest) returns (UpdateClockResponse);
}
