# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

<<<<<<<< Updated upstream:utils/pb/fraud_detection/fraud_detection_pb2_grpc.py
import fraud_detection_pb2 as fraud__detection__pb2
========
import fraud_pb2 as fraud__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fraud_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )
>>>>>>>> Stashed changes:utils/pb/src/fraud_pb2_grpc.py


class HelloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
<<<<<<<< Updated upstream:utils/pb/fraud_detection/fraud_detection_pb2_grpc.py
        self.SayHello = channel.unary_unary(
                '/hello.HelloService/SayHello',
                request_serializer=fraud__detection__pb2.HelloRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.HelloResponse.FromString,
                )
========
        self.CheckFraud = channel.unary_unary(
                '/fraud.FraudChecker/CheckFraud',
                request_serializer=fraud__pb2.FraudRequest.SerializeToString,
                response_deserializer=fraud__pb2.FraudResponse.FromString,
                _registered_method=True)
>>>>>>>> Stashed changes:utils/pb/src/fraud_pb2_grpc.py


class HelloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=fraud__detection__pb2.HelloRequest.FromString,
                    response_serializer=fraud__detection__pb2.HelloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hello.HelloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud.FraudChecker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
<<<<<<<< Updated upstream:utils/pb/fraud_detection/fraud_detection_pb2_grpc.py
        return grpc.experimental.unary_unary(request, target, '/hello.HelloService/SayHello',
            fraud__detection__pb2.HelloRequest.SerializeToString,
            fraud__detection__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
========
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud.FraudChecker/CheckFraud',
            fraud__pb2.FraudRequest.SerializeToString,
            fraud__pb2.FraudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
>>>>>>>> Stashed changes:utils/pb/src/fraud_pb2_grpc.py
