# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"\x97\x01\n\x12TransactionRequest\x12>\n\ncreditCard\x18\x01 \x01(\x0b\x32*.transaction.TransactionRequest.CreditCard\x1a\x41\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"&\n\x13TransactionResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x32m\n\x13TransactionVerifier\x12V\n\x11VerifyTransaction\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=35
  _globals['_TRANSACTIONREQUEST']._serialized_end=186
  _globals['_TRANSACTIONREQUEST_CREDITCARD']._serialized_start=121
  _globals['_TRANSACTIONREQUEST_CREDITCARD']._serialized_end=186
  _globals['_TRANSACTIONRESPONSE']._serialized_start=188
  _globals['_TRANSACTIONRESPONSE']._serialized_end=226
  _globals['_TRANSACTIONVERIFIER']._serialized_start=228
  _globals['_TRANSACTIONVERIFIER']._serialized_end=337
# @@protoc_insertion_point(module_scope)
