syntax = "proto3";

package booksdb;

service BooksDatabase {
  rpc Read (ReadRequest) returns (ReadResponse);
  rpc Write (WriteRequest) returns (WriteResponse);


  rpc Prepare(TransactionRequest) returns (PrepareResponse);
  rpc Commit(TransactionRequest) returns (CommitResponse);
  rpc Abort(TransactionRequest) returns (AbortResponse);
}

message ReadRequest {
  string title = 1;
}

message ReadResponse {
  int32 stock = 1;
}

message WriteRequest {
  string title = 1;
  int32 new_stock = 2;
}

message WriteResponse {
  bool success = 1;
}
message TransactionRequest {
  string order_id = 1;
  string title = 2;
  int32 new_stock = 3;
}

message PrepareResponse {
  bool ready = 1;
}

message CommitResponse {
  bool success = 1;
  string message = 2;
}

message AbortResponse {
  bool aborted = 1;
  string message = 2;
}
