# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"A\n\x12TransactionRequest\x12+\n\ncreditCard\x18\x01 \x01(\x0b\x32\x17.transaction.CreditCard\"&\n\x13TransactionResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\x32l\n\x12TransactionService\x12V\n\x11VerifyTransaction\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREDITCARD']._serialized_start=34
  _globals['_CREDITCARD']._serialized_end=99
  _globals['_TRANSACTIONREQUEST']._serialized_start=101
  _globals['_TRANSACTIONREQUEST']._serialized_end=166
  _globals['_TRANSACTIONRESPONSE']._serialized_start=168
  _globals['_TRANSACTIONRESPONSE']._serialized_end=206
  _globals['_TRANSACTIONSERVICE']._serialized_start=208
  _globals['_TRANSACTIONSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
