# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification/transaction_verification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'transaction_verification/transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7transaction_verification/transaction_verification.proto\"$\n\x12TransactionRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\"\'\n\x13TransactionResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32Y\n\x17TransactionVerification\x12>\n\x11VerifyTransaction\x12\x13.TransactionRequest\x1a\x14.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification.transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=59
  _globals['_TRANSACTIONREQUEST']._serialized_end=95
  _globals['_TRANSACTIONRESPONSE']._serialized_start=97
  _globals['_TRANSACTIONRESPONSE']._serialized_end=136
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=138
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=227
# @@protoc_insertion_point(module_scope)
