# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import order_executor_pb2 as order__executor__pb2


class OrderExecutorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnnounceID = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/AnnounceID',
                request_serializer=order__executor__pb2.AnnounceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.CoordinatorAnnouncement = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/CoordinatorAnnouncement',
                request_serializer=order__executor__pb2.CoordinatorMessage.SerializeToString,
                response_deserializer=order__executor__pb2.CoordinatorResponse.FromString,
                )
        self.DequeueOrder = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/DequeueOrder',
                request_serializer=order__executor__pb2.DequeueRequest.SerializeToString,
                response_deserializer=order__executor__pb2.DequeueResponse.FromString,
                )
        self.Dequeue = channel.unary_unary(
                '/orderexecutor.OrderExecutorService/Dequeue',
                request_serializer=order__executor__pb2.DequeueRequest.SerializeToString,
                response_deserializer=order__executor__pb2.DequeueResponse.FromString,
                )


class OrderExecutorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnnounceID(self, request, context):
        """RPC for other executors to announce their ID during an election
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CoordinatorAnnouncement(self, request, context):
        """RPC to announce new leader to all nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DequeueOrder(self, request, context):
        """The RPC to dequeue orders (only leader should execute it)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dequeue(self, request, context):
        """RPC to process an order that's been dequeued by the leader
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnnounceID': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceID,
                    request_deserializer=order__executor__pb2.AnnounceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CoordinatorAnnouncement': grpc.unary_unary_rpc_method_handler(
                    servicer.CoordinatorAnnouncement,
                    request_deserializer=order__executor__pb2.CoordinatorMessage.FromString,
                    response_serializer=order__executor__pb2.CoordinatorResponse.SerializeToString,
            ),
            'DequeueOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.DequeueOrder,
                    request_deserializer=order__executor__pb2.DequeueRequest.FromString,
                    response_serializer=order__executor__pb2.DequeueResponse.SerializeToString,
            ),
            'Dequeue': grpc.unary_unary_rpc_method_handler(
                    servicer.Dequeue,
                    request_deserializer=order__executor__pb2.DequeueRequest.FromString,
                    response_serializer=order__executor__pb2.DequeueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderexecutor.OrderExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrderExecutorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnnounceID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/AnnounceID',
            order__executor__pb2.AnnounceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CoordinatorAnnouncement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/CoordinatorAnnouncement',
            order__executor__pb2.CoordinatorMessage.SerializeToString,
            order__executor__pb2.CoordinatorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DequeueOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/DequeueOrder',
            order__executor__pb2.DequeueRequest.SerializeToString,
            order__executor__pb2.DequeueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dequeue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/orderexecutor.OrderExecutorService/Dequeue',
            order__executor__pb2.DequeueRequest.SerializeToString,
            order__executor__pb2.DequeueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
