# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\rorderexecutor\x1a\x1bgoogle/protobuf/empty.proto\"O\n\x05Order\x12\x0f\n\x07orderId\x18\x01 \x01(\t\x12\x10\n\x08userName\x18\x02 \x01(\t\x12\x11\n\tbookTitle\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"&\n\x0f\x41nnounceRequest\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\x05\"K\n\x0e\x44\x65queueRequest\x12\x14\n\x0crequest_data\x18\x01 \x01(\t\x12#\n\x05order\x18\x02 \x01(\x0b\x32\x14.orderexecutor.Order\"V\n\x0f\x44\x65queueResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x12\x65xecuted_by_leader\x18\x02 \x01(\x08\x12\x16\n\x0eorder_received\x18\x03 \x01(\x08\"\'\n\x12\x43oordinatorMessage\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"+\n\x13\x43oordinatorResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"D\n\x18\x41re_You_AvailableRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x15\n\rrequest_to_id\x18\x02 \x01(\t\"V\n\x19\x41re_You_AvailableResponse\x12\x13\n\x0b\x65xecutor_id\x18\x01 \x01(\t\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x11\n\tavailable\x18\x03 \x01(\x08\"\'\n\x0f\x45lectionRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\"(\n\x10\x45lectionResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xd7\x02\n\x14OrderExecutorService\x12\x44\n\nAnnounceID\x12\x1e.orderexecutor.AnnounceRequest\x1a\x16.google.protobuf.Empty\x12`\n\x17\x43oordinatorAnnouncement\x12!.orderexecutor.CoordinatorMessage\x1a\".orderexecutor.CoordinatorResponse\x12M\n\x0c\x44\x65queueOrder\x12\x1d.orderexecutor.DequeueRequest\x1a\x1e.orderexecutor.DequeueResponse\x12H\n\x07\x44\x65queue\x12\x1d.orderexecutor.DequeueRequest\x1a\x1e.orderexecutor.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDER']._serialized_start=68
  _globals['_ORDER']._serialized_end=147
  _globals['_ANNOUNCEREQUEST']._serialized_start=149
  _globals['_ANNOUNCEREQUEST']._serialized_end=187
  _globals['_DEQUEUEREQUEST']._serialized_start=189
  _globals['_DEQUEUEREQUEST']._serialized_end=264
  _globals['_DEQUEUERESPONSE']._serialized_start=266
  _globals['_DEQUEUERESPONSE']._serialized_end=352
  _globals['_COORDINATORMESSAGE']._serialized_start=354
  _globals['_COORDINATORMESSAGE']._serialized_end=393
  _globals['_COORDINATORRESPONSE']._serialized_start=395
  _globals['_COORDINATORRESPONSE']._serialized_end=438
  _globals['_ARE_YOU_AVAILABLEREQUEST']._serialized_start=440
  _globals['_ARE_YOU_AVAILABLEREQUEST']._serialized_end=508
  _globals['_ARE_YOU_AVAILABLERESPONSE']._serialized_start=510
  _globals['_ARE_YOU_AVAILABLERESPONSE']._serialized_end=596
  _globals['_ELECTIONREQUEST']._serialized_start=598
  _globals['_ELECTIONREQUEST']._serialized_end=637
  _globals['_ELECTIONRESPONSE']._serialized_start=639
  _globals['_ELECTIONRESPONSE']._serialized_end=679
  _globals['_ORDEREXECUTORSERVICE']._serialized_start=682
  _globals['_ORDEREXECUTORSERVICE']._serialized_end=1025
# @@protoc_insertion_point(module_scope)
