# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import fraud_pb2 as fraud__pb2


class FraudCheckerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckFraud = channel.unary_unary(
                '/fraud.FraudChecker/CheckFraud',
                request_serializer=fraud__pb2.FraudRequest.SerializeToString,
                response_deserializer=fraud__pb2.FraudResponse.FromString,
                )


class FraudCheckerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudCheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFraud,
                    request_deserializer=fraud__pb2.FraudRequest.FromString,
                    response_serializer=fraud__pb2.FraudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.FraudChecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudChecker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud.FraudChecker/CheckFraud',
            fraud__pb2.FraudRequest.SerializeToString,
            fraud__pb2.FraudResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
